### ISSUE TITLE
Get tests to pass on CI

### ISSUE THREAD

**Issue by jccfd** [ESUG/Regis#22]
Some tests are failing in the image even if they pass in the image. This should be investigated

**Comment by Ducasse** [comment]
We fixed some of them with a group but they did not send a PR :(
I will insist that they do it.

**Comment by jccfd** [comment]
That would be nice indeed so that I do not redo something done :)

**Comment by Ducasse** [comment]
Yes it was about the tests about CVS and some were adding new tests for passwords generation

**Comment by jccfd** [comment]
I talked about that with Gaylord
I'll avoid to touch failing tests for now since he works on it and check the tests in errors

New tests will not impact me

**Comment by jccfd** [comment]
In my local image now I have 0 red test and 10 yellow tests. 

Gaylord told me he had a solution for some yellow tests so I'll not touch them before he does his PR

**Comment by jccfd** [comment]
Done
