### ISSUE TITLE
Registration: Membership type displayed as "nil" by default

### ISSUE THREAD

**Issue by jccfd** [ESUG/Regis#23]
When registering I see "nil" selected by default when selecting the registration type. 
IMO it should either select "Other" by default or display "Select registration type" instead of nil.

**Comment by xvsyyghs** [comment]
Hi, i want to fix this issue if it's possible, I am a member of a group in the course C3P

**Comment by jccfd** [comment]
Fixed in 03aa844e67b4b35a3207c3d778c05cdb49889258
