### ISSUE TITLE
Move CI to Github Actions

### ISSUE THREAD

**Issue by jccfd** [ESUG/Regis#3]

**Comment by Ducasse** [comment]
Yes I was thinking about this too.

**Comment by Ducasse** [comment]
Cyril I thought that you told me that the GH actions were working.
But I cannot find them.

**Comment by jccfd** [comment]
I just added the action but the tests are not yet green.I need to check why

**Comment by jordanmontt** [comment]
Is this still relevant? I see that the CI is using github actions now.

**Comment by jecisc** [comment]
This is done
