### ISSUE TITLE
Does not load on P10

### ISSUE THREAD

**Issue by Ducasse** [ESUG/Regis#4]
Cannot load 

```
Metacello new  
    baseline: 'ESUGApp';
    githubUser: 'ESUG' project: 'Regis' commitish: 'master' path: 'src';
    onWarningLog;
    onConflictUseLoaded;
    load.
```

When I 

<img width="1267" alt="Capture 2022-10-13 at 11 43 36" src="https://user-images.githubusercontent.com/432549/195563121-61a7087b-bb41-4946-830f-f510d1a749eb.png">

**Comment by jccfd** [comment]
Do you use already cloned projects or does it does a clean installation? A new MDL version was released to fix this bug a few days ago and I cannot reproduce

**Comment by jccfd** [comment]
I'm able to load it. Let's reopen if it happens again in the future
